version: '3.7'
services:
  data-prepper:
    image: opensearchproject/data-prepper:2
    container_name: data-prepper
    volumes:
      - ./log_pipeline.yaml:/usr/share/data-prepper/pipelines/log_pipeline.yaml
    ports:
      - 2021:2021
    networks:
    - test-net

networks:
  test-net:
    driver: bridge
